---
- hosts: all
  become: true

  tasks:
    - name: Install Steam
      dnf:
        name: steam
        state: present
    - name: Install Lutris
      dnf:
        name: lutris
        state: present
    - name: Install MangoHud
      dnf:
        name: mangohud
        state: present
    - name: Install vkBasalt
      dnf:
        name: vkbasalt
        state: present
    - name: Install GameMode
      dnf:
        name: gamemode
        state: present  
    - name: Install Steam-Devices
      dnf:
        name: steam-devices
        state: present
