---
- hosts: all
  become: true

  tasks:
    - name: Install nvidia RPM fusion drivers
      dnf:
        name: xorg-x11-drv-nvidia
        state: present
    - name: Install akmod-nvidia
      dnf:
        name: akmod-nvidia
        state: present
    - name: Install cuda libs from rpm-fusion
      dnf:
        name: xorg-x11-drv-nvidia-cuda-libs
        state: present
    - name: Install nvtop
      dnf:
        name: nvtop
        state: present
