---
- hosts: all
  become: true
  tasks:
    - name: Add multimedia libraries
      command: dnf group install multimedia -y

    - name: Install VLC
      dnf:
        name: vlc
        state: present

    - name: Install MPV
      dnf:
        name: mpv
        state: present

    - name: Install handbrake
      dnf:
        name: handbrake
        state: present

    - name: Install handbrake-gui
      dnf:
        name: handbrake-gui
        state: present
